In [1]:
import numpy as np


In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [2]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr.ndim

1

In [6]:
matrix.ndim

2

In [5]:
arr.shape

(5,)

In [7]:
matrix.shape

(3, 3)

In [8]:
arr.size

5

In [9]:
matrix.size

9

In [10]:
arr.dtype

dtype('int64')

In [11]:
matrix.dtype

dtype('int64')

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [14]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [15]:
var1=np.full((2,3),1)
var1

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [21]:
np.linspace(25,101,12)

array([ 25.        ,  31.90909091,  38.81818182,  45.72727273,
        52.63636364,  59.54545455,  66.45454545,  73.36363636,
        80.27272727,  87.18181818,  94.09090909, 101.        ])

In [22]:
np.linspace(0,1,54)

array([0.        , 0.01886792, 0.03773585, 0.05660377, 0.0754717 ,
       0.09433962, 0.11320755, 0.13207547, 0.1509434 , 0.16981132,
       0.18867925, 0.20754717, 0.22641509, 0.24528302, 0.26415094,
       0.28301887, 0.30188679, 0.32075472, 0.33962264, 0.35849057,
       0.37735849, 0.39622642, 0.41509434, 0.43396226, 0.45283019,
       0.47169811, 0.49056604, 0.50943396, 0.52830189, 0.54716981,
       0.56603774, 0.58490566, 0.60377358, 0.62264151, 0.64150943,
       0.66037736, 0.67924528, 0.69811321, 0.71698113, 0.73584906,
       0.75471698, 0.77358491, 0.79245283, 0.81132075, 0.83018868,
       0.8490566 , 0.86792453, 0.88679245, 0.90566038, 0.9245283 ,
       0.94339623, 0.96226415, 0.98113208, 1.        ])

In [23]:
arr = np.array([1,2,3] , dtype = float)
arr

array([1., 2., 3.])

In [24]:
arr.astype(int)

array([1, 2, 3])

In [25]:
arr =  np.array([10,20,30,40,50])

In [26]:
arr[0]

np.int64(10)

In [27]:
arr[-1]

np.int64(50)

In [28]:
arr[1:4]

array([20, 30, 40])

In [29]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
mat[0,1]

np.int64(2)

In [31]:
mat[:,1]

array([2, 5, 8])

In [32]:
mat[1:,:2]

array([[4, 5],
       [7, 8]])

In [33]:
arr = np.array([5,10,15,20])
arr

array([ 5, 10, 15, 20])

In [34]:
arr[arr>10]

array([15, 20])

In [35]:
mat[mat % 2 ==0]

array([2, 4, 6, 8])

In [36]:
mat[mat % 2 ==1]

array([1, 3, 5, 7, 9])

In [37]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [38]:
a+b

array([5, 7, 9])

In [39]:
a>2

array([False, False,  True])

In [40]:
a==3

array([False, False,  True])

In [41]:
arr = np.array([1,2,3])
arr + 10

array([11, 12, 13])

In [42]:
mat = np.array([[1,2,3],[4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
mat + np.array([10,20,30])

array([[11, 22, 33],
       [14, 25, 36]])

In [44]:
arr.sum()

np.int64(6)

In [45]:
arr.mean()

np.float64(2.0)

In [47]:
arr.min()


np.int64(1)

In [48]:
arr.max()

np.int64(3)

In [49]:
arr.std()

np.float64(0.816496580927726)

In [50]:
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
mat.sum(axis=1)

array([ 6, 15])

In [56]:
np.arange(12)
arr

array([1, 2, 3])

In [59]:
arr = np.arange(12)
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
arr = np.arange(24)

In [64]:
arr.reshape((3,2,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [65]:
arr.reshape((2,3,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [67]:
mat.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [68]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [69]:
a

array([1, 2, 3])

In [70]:
b

array([4, 5, 6])

In [71]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [72]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [74]:
np.split(np.arange(10),2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [75]:
a = np.array([1,2,3])
b=a
b[0]=100

In [76]:
a

array([100,   2,   3])

In [77]:
b

array([100,   2,   3])

In [78]:
c = a.copy()

In [81]:
b[0]=200

In [82]:
a

array([200,   2,   3])

In [83]:
b

array([200,   2,   3])

In [84]:
np.random.rand(3)

array([0.16574086, 0.38893769, 0.90323827])

In [85]:
np.random.randn(3)

array([ 0.11553675, -0.33575887,  0.17733828])

In [88]:
np.random.randint(0,10,size = (3,3,2,5))

array([[[[0, 6, 7, 6, 5],
         [9, 5, 4, 8, 7]],

        [[1, 7, 1, 0, 7],
         [4, 3, 4, 7, 7]],

        [[3, 0, 7, 6, 4],
         [2, 6, 4, 1, 8]]],


       [[[4, 7, 8, 9, 9],
         [4, 1, 6, 4, 7]],

        [[4, 6, 1, 2, 7],
         [2, 8, 5, 3, 4]],

        [[9, 1, 0, 4, 3],
         [2, 7, 9, 3, 9]]],


       [[[4, 4, 0, 4, 3],
         [7, 7, 0, 8, 0]],

        [[8, 8, 4, 6, 0],
         [5, 1, 5, 1, 7]],

        [[3, 8, 6, 1, 5],
         [3, 6, 5, 3, 2]]]])

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,9]])

In [91]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [95]:
B = np.array([[5,6],[7,9]])
np.dot(A,B)

array([[19, 24],
       [43, 54]])

In [93]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [94]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])